Fix Makefile.am stringize glsl header gen command to specify filename
Running `make` results in:

  GEN      glyphy-common-glsl.h
Traceback (most recent call last):
  File "/home/user/glyphy/src/./stringize", line 6, in <module>
    filename = sys.argv[2]
IndexError: list index out of range
make: *** [Makefile:874: glyphy-common-glsl.h] Error 1

Adds error handling:

  GEN      glyphy-common-glsl.h
stringize: missing filename: ['./stringize', 'static const char *glyphy_common_glsl']
make: *** [Makefile:874: glyphy-common-glsl.h] Error 1

Fixes stringize command in Makefile.am